import type Editor from '../../../src/editor'
import { ElementType } from '../../../src/editor/dataset/enum/Element'
import { RowFlex } from '../../../src/editor/dataset/enum/Row'

function text(value: string, options: Record<string, unknown> = {}) {
  return value.split('').map(char => ({
    value: char,
    ...options
  }))
}

function line(value: string, options: Record<string, unknown> = {}) {
  return [...text(value, options), { value: '\n', ...options }]
}

function cell(
  value: string,
  options: {
    colspan?: number
    rowspan?: number
    height?: number
    backgroundColor?: string
    rowFlex?: RowFlex
    bold?: boolean
    size?: number
  } = {}
) {
  const {
    colspan = 1,
    rowspan = 1,
    backgroundColor,
    rowFlex = RowFlex.CENTER,
    bold,
    size
  } = options
  return {
    colspan,
    rowspan,
    backgroundColor,
    value: text(value, {
      rowFlex,
      bold,
      size
    })
  }
}

function tr(tdList: ReturnType<typeof cell>[], height = 24) {
  return {
    height,
    tdList
  }
}

describe('issue #390 dynamic table data boundary', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000/canvas-editor/')
    cy.get('canvas[data-index]').first().as('canvas').should('have.length', 1)
  })

  it('can render a table generated by application code through setValue', () => {
    cy.getEditor().then((editor: Editor) => {
      const rows = [
        ['项目', '数量', '金额'],
        ['检查费', '1', '20.00'],
        ['治疗费', '2', '50.00']
      ]

      editor.command.executeSetValue({
        main: [
          {
            value: '',
            type: ElementType.TABLE,
            colgroup: [{ width: 120 }, { width: 120 }, { width: 120 }],
            trList: rows.map(row => ({
              height: 40,
              tdList: row.map(value => ({
                colspan: 1,
                rowspan: 1,
                value: [{ value }]
              }))
            }))
          }
        ]
      })

      const value = editor.command.getValue().data.main
      const table = value[0]
      expect(table.type).to.eq(ElementType.TABLE)
      expect(table.trList).to.have.length(3)
      expect(table.trList?.[2].tdList[2].value[0].value).to.eq('50.00')
      expect(editor.command.getText().main).to.contain('检查费')
      expect(editor.command.getText().main).to.contain('20.00')
    })

    cy.wait(300)
    cy.screenshot('issue-390-dynamic-table-data-rendered', {
      capture: 'viewport'
    })
  })

  it('can render a treatment record form generated by application code', () => {
    cy.getEditor().then((editor: Editor) => {
      const records = [
        ['2023-12-22', 'DZSW', '腰部 颈部', '6 mA', '20 min', '王医生'],
        ['2023-12-22', 'CDB', '腰部 颈部', '55 mA', '20 min', '王医生'],
        ['2023-12-22', 'CSB', '腰部 颈部', '0.25 w/cm²', '20 min', '李医生'],
        ['2023-12-23', 'DZSW', '腰部 颈部', '6 mA', '20 min', '王医生'],
        ['2023-12-23', 'WB', '腰部 骶部 颈部 背部', '5 w', '15 min', '赵医生'],
        ['2023-12-24', 'ZYDX', '腰部 骶部 颈部 背部', '6 mA', '20 min', '李医生'],
        ['2023-12-24', 'CDB', '腰部 颈部', '55 mA', '20 min', '王医生'],
        ['2023-12-25', 'CSB', '腰部 颈部', '0.25 w/cm²', '20 min', '赵医生'],
        ['2023-12-25', 'WB', '腰部 骶部 颈部 背部', '5 w', '15 min', '王医生'],
        ['2023-12-26', 'ZYDX', '腰部 骶部 颈部 背部', '6 mA', '20 min', '李医生'],
        ['2023-12-26', 'DZSW', '腰部 颈部', '6 mA', '20 min', '王医生'],
        ['2024-01-08', 'WB', '腰部 骶部 颈部 背部', '5 w', '15 min', '赵医生']
      ]

      editor.command.executeSetValue({
        main: [
          ...line('第一人民医院', {
            rowFlex: RowFlex.CENTER,
            size: 24,
            bold: true
          }),
          ...line('物理因子治疗记录单', {
            rowFlex: RowFlex.CENTER,
            size: 16,
            bold: true
          }),
          ...line('科别：康复科        姓名：张某某        出生年月日：1956年06月26日', {
            size: 12
          }),
          ...line('病案号：BL-001       性别：女          年龄：67岁        床号：3床', {
            size: 12
          }),
          {
            value: '',
            type: ElementType.TABLE,
            colgroup: [
              { width: 86 },
              { width: 74 },
              { width: 154 },
              { width: 112 },
              { width: 76 },
              { width: 72 }
            ],
            trList: [
              tr([
                cell('临床诊断：腰椎间盘突出', {
                  colspan: 6,
                  rowFlex: RowFlex.LEFT,
                  bold: true
                })
              ], 28),
              tr([
                cell('日期', { bold: true, backgroundColor: '#F3F4F6' }),
                cell('治疗项目', { bold: true, backgroundColor: '#F3F4F6' }),
                cell('部位', { bold: true, backgroundColor: '#F3F4F6' }),
                cell('剂量', { bold: true, backgroundColor: '#F3F4F6' }),
                cell('治疗时间', { bold: true, backgroundColor: '#F3F4F6' }),
                cell('操作者', { bold: true, backgroundColor: '#F3F4F6' })
              ], 28),
              ...records.map(record => tr(record.map(value => cell(value)), 24)),
              tr([
                cell('不良反应及处理：', {
                  colspan: 6,
                  rowFlex: RowFlex.LEFT,
                  bold: true
                })
              ], 38),
              tr([
                cell('疗效评估：      评估人：          评估时间：     年     月     日     时     分', {
                  colspan: 6,
                  rowFlex: RowFlex.LEFT,
                  bold: true
                })
              ], 46),
              tr([
                cell(
                  '备注：表格中的治疗项目分别用治疗项目的英文缩写或拼音的第一个字母大写表示，具体如下：低频脉冲电治疗(DPMC)；中频脉冲电治疗(ZPMC)；中医定向药透疗法(ZYDX)；电子生物反馈疗法(DZSW)；超短波治疗(CDB)；超声波治疗(CSB)；激光治疗(JG)；牵引(QY)；紫外线治疗(ZWX)；红外线治疗(HWX)；磁热疗法(CR)；经颅重复磁刺激(JLC)；微波治疗(WB)。',
                  {
                    colspan: 6,
                    rowFlex: RowFlex.LEFT,
                    size: 11
                  }
                )
              ], 76)
            ]
          },
          ...line('文件编号：BL-BD-ZK-532    版本号：1.0', {
            size: 12
          })
        ]
      })

      const value = editor.command.getValue().data.main
      const table = value.find(element => element.type === ElementType.TABLE)
      expect(table?.trList).to.have.length(records.length + 5)
      expect(editor.command.getText().main).to.contain('物理因子治疗记录单')
      expect(editor.command.getText().main).to.contain('2024-01-08')
      expect(editor.command.getText().main).to.contain('不良反应及处理')
    })

    cy.wait(300)
    cy.screenshot('issue-390-treatment-record-form-rendered', {
      capture: 'viewport'
    })
  })
})
